### ISSUE TITLE
Feature Request: use theme color palette

### ISSUE THREAD

**Issue by eight85** [WoozyMasta/dayz-ctl#10]
Tool works great on Kubuntu 22.10 with backports and all. Would it be possible to use your own color palette for your tool? Would be nice to use Catppuccin theme as it supports many terminals and other cli tools. https://github.com/catppuccin/catppuccin

**Comment by WoozyMasta** [comment]
Customization of themes will work fine for fzf but not for gum especially with markdown rendering, because of this the style is made in one pink style
