### ISSUE TITLE
missing dependency fzf-preview

### ISSUE THREAD

**Issue by airtonix** [WoozyMasta/dayz-ctl#11]
![image](https://user-images.githubusercontent.com/61225/226504750-b5cb5200-09d3-4826-afca-0a8175bef0ac.png)

**Comment by airtonix** [comment]
ok it's not another dependency, but due to how you're trying to run local functions. 

https://github.com/WoozyMasta/dayz-ctl/blob/master/dayz-ctl#L519

https://github.com/junegunn/fzf/issues/1337#issuecomment-407604686

**Comment by WoozyMasta** [comment]
Actually the `fzfPreview` function is exported here [#L1387](https://github.com/WoozyMasta/dayz-ctl/blob/master/dayz-ctl#L1387)

I see that the error in the screenshot is from zsh, and I think it's worth running the launcher in bash
