### ISSUE TITLE
Steam root at $HOME is assumed

### ISSUE THREAD

**Issue by master-of-zen** [WoozyMasta/dayz-ctl#14]
I use steam library at my SSD which is not the same device on which my system is located which results in error : `DayZ not installed or cant find it`
What can i do?)

**Comment by master-of-zen** [comment]
I moved dayz to my system drive, after that i got first launch of dayz-ctl

**Comment by WoozyMasta** [comment]
duplicate https://github.com/WoozyMasta/dayz-ctl/issues/9
