### ISSUE TITLE
FR: add launch option for FSR

### ISSUE THREAD

**Issue by hofleverancier** [WoozyMasta/dayz-ctl#15]
According to https://support.system76.com/articles/use-amd-fsr/ one can run Proton games using FSR using either:

`WINE_FULLSCREEN_FSR=1 %command%`
or
`WINE_FULLSCREEN_FSR=1 WINE_FULLSCREEN_FSR_STRENGTH=1 %command%`
Where the latter allows to set sharpening level.

It would be absolutely wonderful if this could be incorporated into dayzctl, a launcher I gratefully use nearly every day :)
Or maybe allow setting a custom launch option in addition to the existing list.

**Comment by WoozyMasta** [comment]
I'm not quite sure how this relates to the Launcher. You can set these variables in the startup parameters for DayZ in Steam, or define them globally in your .profile or .bashrc.
Does it make sense to make another place to control these parameters? Yeah and the list of all possible variables is hard to predict, it seems like it would just add to the problem.

**Comment by hofleverancier** [comment]
Thanks, I assumed the steam launch options would be ignored when using the launcher, from your message I gather they are not.
